apiVersion: apps/v1
kind: Deployment
metadata:
  name: userapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userapi
  template:
    metadata:
      labels:
        app: userapi
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: acr0099-userapi-container
          image: acr0099.azurecr.io/userapi
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userapi
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: userapi